services:
  node-typescript:
    # container_name: node-typescript
    build:
      context: .
      target: development
    # env_file:
    #   - ./.env
    image: node-typescript:dev
    ports:
      - "5001:5001"
    volumes:
      - .:/app
      - /app/node_modules # prevents node_modules overwrite.
    command: npm run local:watch
